version: '3'
services:
  java_app:
    container_name: java_app
    build: ./
    depends_on:
      - postgres
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      # DDL_AUTO: create
      # DDL_ACTION: drop-and-create
      DDL_AUTO: validate
      DDL_ACTION: none
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_DB: postgres
    profiles:
      - java_app
      - all
  postgres:
    container_name: postgres
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    profiles:
      - database
      - all
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d     
#
# Extras /docker-entrypoint-initdb.d
#
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@local.org
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8889:80"
    profiles:
      - pgadmin
    volumes:
      - ${temp}:/var/lib/pgadmin
